# Generated by Django 5.1 on 2024-09-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_customerprofile_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='locality',
        ),
    ]
